import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "/globals.css";
import '@/app/globals.css'

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="">
      <body>{children}</body>
    </html>
  )
}
